### ISSUE TITLE
controller matter

### ISSUE THREAD

**Issue by stefano055415** [project-chip/matter.js#1158] opened 2024-09-04 06:50 UTC
Matter.js v 0.10.0

2024-09-04 08:33:52.847 FATAL  Logger               Unhandled error detected: NoResponseTimeoutError
  at TimerNode.callback (/Users/xxx/Desktop/Repo-git/matter_hub/node_modules/@project-chip/matter.js/src/util/Queue.ts:31:26)
  at Timeout.<anonymous> (/Users/xxx/Desktop/Repo-git/matter_hub/node_modules/@project-chip/matter-node.js/src/time/TimeNode.ts:59:18)
  at listOnTimeout (node:internal/timers:573:17)
  at process.processTimers (node:internal/timers:514:7)
/Users/xxx/Desktop/Repo-git/matter_hub/node_modules/@project-chip/matter.js/src/util/Queue.ts:31
                rejecter(new NoResponseTimeoutError()),
                         ^

NoResponseTimeoutError
    at TimerNode.callback (/Users/xxx/Desktop/Repo-git/matter_hub/node_modules/@project-chip/matter.js/src/util/Queue.ts:31:26)
    at Timeout.<anonymous> (/Users/xxx/Desktop/Repo-git/matter_hub/node_modules/@project-chip/matter-node.js/src/time/TimeNode.ts:59:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

If I try to disable the controller's wifi (pc) instead of receiving the node disconnection event the process is interrupted because this error is not handled

**Comment by stefano055415** [comment] 2024-09-04 12:20
Hi @Apollon77, 

let me explain

I started the node matter controller example, I associated a device (in my case a merros socket)
I turned off the pc wifi (I have no other active network cards)
After about 1 minute it loses communication with the re-registration to all attributes and events

I don't know why, but it doesn't break like before

when the wifi is restored, the registration to events is not restored anyway


2024-09-04 14:10:28.873 DEBUG  MdnsScanner          Found commissionable device 9D5ACBF4B55E3A7F._matterc._udp.local with data: SII: 500 SAI: 300 SAT: 4000 T: 0 DT: 14 PH: 33 ICD: 0 VP: 65521+32768 DN: Matter test device RI: undefined PI: 
2024-09-04 14:11:03.694 INFO   InteractionClient    Subscription 2401470688 timed out ...
2024-09-04 14:11:03.695 INFO   PairedNode           Node 2410673071589895403: Subscription update not received ...
2024-09-04 14:11:03.697 DEBUG  MessageExchange      New exchange channel: udp://fe80::4ae1:e9ff:fedb:e3fc%en0:5540 on session secure/51816 protocol: 1 id: 19290 session: secure/51816 peerSessionId: 58894 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
2024-09-04 14:11:03.697 DEBUG  InteractionClient    Sending subscribe request: attributes: */*/* and events: !*/*/*
2024-09-04 14:11:03.698 DEBUG  ExchangeManager      Message » id: 58894/19290/265467992 type: 1/3 acked: undefined reqAck: true duplicate: false payload: 15290024010024023c360317181836041729041818290724ff0c18
2024-09-04 14:11:03.706 INFO   PairedNode           Node 2410673071589895403: Error resubscribing to all attributes and events send EHOSTUNREACH fe80::4ae1:e9ff:fedb:e3fc%en0:5540
  at doSend (node:dgram:717:16)
  at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
  at afterDns (node:dgram:663:5)
  at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Restore wifi connection

2024-09-04 14:12:34.066 DEBUG  MdnsScanner          Adding operational device 7DC81C96EC4344B1-0BC7C68BEC564407._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.069 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-00000000871CCC9F._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.070 DEBUG  MdnsScanner          Adding operational device 9C2F053B0E2C7E6F-01FEFF078BC6EFBA._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.070 DEBUG  MdnsScanner          Adding operational device EF8458602EE56D33-00000000C5F355F3._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.071 DEBUG  MdnsScanner          Adding operational device D89A675ECAB22AD1-000000000000001B._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.073 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-000000000C3D3A1C._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.074 DEBUG  MdnsScanner          Adding operational device EF8458602EE56D33-00000000D9D41861._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.075 DEBUG  MdnsScanner          Adding operational device 7DC81C96EC4344B1-072C076CA309F7E3._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.075 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-00000000ED2F7103._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.076 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-0000000004BD9CA3._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.076 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-000000009A0DA5E0._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.076 DEBUG  MdnsScanner          Adding operational device EF8458602EE56D33-0000000044BF1D7D._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.077 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-00000000F72198A3._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.077 DEBUG  MdnsScanner          Adding operational device EF8458602EE56D33-000000001DD8BAB4._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.077 DEBUG  MdnsScanner          Adding operational device EF8458602EE56D33-00000000D2F5904C._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.078 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-00000000FFAF4290._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.078 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-000000003F2631AB._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.078 DEBUG  MdnsScanner          Adding operational device 33368E02EFC7008C-21746E62E5B72CEB._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: 4933+40962 DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.079 DEBUG  MdnsScanner          Adding operational device 98C3F1112E53A2DE-00000000C3F269BD._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-09-04 14:12:34.166 DEBUG  MdnsScanner          Adding operational device 7DC81C96EC4344B1-0DA754A46D4CCFCA._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined

**Comment by Apollon77** [comment] 2024-09-05 09:50
ok to your points:
1.) can not repro the initial exception ... hm ... that's bad ;-) In fact when you do a call like onOff or such on the remote devcie then exactly such exceptions could happen, so you need to also catch them in your code. DO you do this/could that be the case?
2.) Events are not restored when reconnecting subscription: Yes this was reported and fixed in [v0.10.0](https://github.com/project-chip/matter.js/releases/tag/v0.10.0). Which version do you use?
3.) This is reported in https://github.com/project-chip/matter.js/issues/1152 too and on my list to verify and fix.

**Comment by stefano055415** [comment] 2024-09-05 12:12
The version used is v0.10.0

This is the complete log

- I receive the connected event
- I turn off the device
- after 1 minute I receive the reconnected event (I never see the disconnected event)
- I reconnect the device and shortly after I see the error "PairRetransmissionLimitReachedError"
- from that moment on it no longer tries to reconnect

[logs.txt](https://github.com/user-attachments/files/16893168/logs.txt)

**Comment by Apollon77** [comment] 2024-09-05 12:46
Thank you. I will look into it

**Comment by Apollon77** [comment] 2024-09-05 12:49
PS: Disconnected is only triggered if the node is explicitely shut down or deleted by the developer! Else main comunication form of Matter is UDP, so there is no classical connection and so the detection is not that easy. This means that as soon as you want to do an action we send something to the device and when this is not successful/answered then we assume theh the device is not available and retry the connection. Thats why the status jumps to "Reconnecting". I see no other way then doing it that way because. I will add this also to the documentation of the disconnected state!

**Comment by Apollon77** [comment] 2024-09-05 14:58
Ok to your log ... it shows 

1.) Device discovered and subscribed and initialized, all fine. Subscription 60s
2.) Then you turned off
3.) Subscription 3539634567 timed out ...
4.) try to reastablish subscription with last known address
5.) failed ... Failed to resume device connection with 192.168.86.142:5540, discover the device ... PairRetransmissionLimitReachedError ... and MDNS discovery started because device i considered offline. 

This could already go to Reconnecting as status ... internally this is the "hm ip maybe changed or just rebooted, give it a 60s try to find again". This officially do not encount for Reconnecting status as of now. I might rethink this. But for now "as designed"

6.)  Resume failed, remove all sessions for node 11210124228205407541
7.) Node reconnecting ... means status changed to Reconnecting
8.) He tries again to reach all known addresses ... this is still unsuccesfull
9.) Registered waiter for query B0700EA891640877-9B925C977E2EED35._matter._tcp.local with no timeout ... means: Discovery started without timeout. Means: Ass soon as the devcie announces itself via MDNS on it's restart then it would be detected and connected. Additionally it tries every 10 minutes to use all known addresses.

So that looks ok in general ... but still strange that device was not re-detected ... looking there

you enabled it again and it was also discovered

> 2024-09-05 14:04:16.240 DEBUG  MdnsScanner          Registered waiter for query B0700EA891640877-9B925C977E2EED35._matter._tcp.local with no timeout
> ...
> 2024-09-05 14:04:17.422 DEBUG  MdnsScanner          Adding operational device B0700EA891640877-9B925C977E2EED35._matter._tcp.local in cache (interface en0) with TXT data: SII: undefined SAI: undefined SAT: undefined T: 0 DT: undefined PH: undefined ICD: 0 VP: 4933+40962 DN: undefined RI: undefined PI: undefined
> 2024-09-05 14:04:17.423 DEBUG  MdnsScanner          Finishing waiter for query B0700EA891640877-9B925C977E2EED35._matter._tcp.local, resolving: true

so detected and also found 

> 2024-09-05 14:04:17.425 DEBUG  ControllerDiscovery  Server addresses to try: undefined: udp://fe80::4ae1:e9ff:fedb:e3fc%en0:5540,undefined: udp://192.168.86.142:5540
and then he tried both

problem is here that the device seems to not answer correctly ... in fact in your log I would expect an error at 14:07:18 because the current code should wait up to 180s and then returns ... can you send the log afterwards? In fact the PR #1165 changes this timing already ... so would be worth rechecking after that

**Comment by Apollon77** [comment] 2024-09-21 20:38
Hi,

please have a look at the current nightly build ... npm tag "@dev" ... There might be some adjustments needed (see changelog) and some imports might have changed but controller side on reconnections should be much better and stable. Please have a look ad provide feedback.

Ingo

**Closed** 2024-09-23 06:29 UTC
Labels: question
