### ISSUE TITLE
Failing to commision on Google Home Android

### ISSUE THREAD

**Issue by JimBuzbee** [project-chip/matter.js#237] opened 2023-07-27 18:23 UTC
Fresh July 27 clone of baseline

Success on: Apple, Alexa, SmartThings, Rainmaker
Failure on Google Home. UI starts the process but sticks "forever" on "Connecting to Device"

Log attached.

[ghome.txt](https://github.com/project-chip/matter.js/files/12186593/ghome.txt)

**Comment by Apollon77** [comment] 2023-07-28 09:14
I also stubled over that theoretically as a potential issue with the new clusters, I will investigate!

**Comment by Apollon77** [comment] 2023-07-29 13:56
partly caused by https://github.com/project-chip/matter.js/issues/239

**Comment by Apollon77** [comment] 2023-08-17 16:02
should be fixed in main since longer time

**Closed by Apollon77** 2023-08-17 16:02 UTC
